config/routes.rb
Openadtools::Application.routes.draw do
  
  root "pages#home"
  get "about", to: "pages#about"

  get "link-tracker", to: "tools#linktracker", as: "linktracker"
  get "encoder-decoder", to: "tools#encoderdecoder", as: "encoderdecoder"
  get "ab-significance", to: "tools#absignificance", as: "absignificance"
  get "follower-finder", to: "tools#followerfinder", as: "followerfinder"
  get "tab-to-csv", to: "tools#tabtocsv", as: "tabtocsv"
  get "campaign-calculator", to: "tools#campaigncalculator", as: "campaigncalculator"
  get "budget-runrate", to: "tools#budgetrunrate", as: "budgetrunrate"
  get "bar-chart", to: "tools#barchart", as: "barchart"
  get "line-chart", to: "tools#linechart", as: "linechart"
  get "tab-to-json", to: "tools#tabtojson", as: "tabtojson"
  get "csv-to-json", to: "tools#csvtojson", as: "csvtojson"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def linktracker
  end

  def encoderdecoder
  end

  def absignificance
  end

  def tabtocsv
  end

  def followerfinder
  end

  def campaigncalculator
  end

  def budgetrunrate
  end

  def barchart
  end

  def linechart
  end

  def adchat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50065936-1', 'openadtools.com');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

  var actionLabel = window.location.pathname;

  // Button Event Track - every button has class "submit btn"
  $('.submit.btn').on('click', function() {
    actionLabel = window.location.pathname;
    ga('send', 'event', 'tool', 'button-submit', actionLabel);
  });

  // Track Navbar Signup Button
  $('#newsletter-signup').on('click', function() {
    ga('send', 'event', 'subscribe', 'start', 'navbar');
  });

</script>

app/views/layouts/_disclaimer.html.erb
<div class="disclaimer">
	<hr>

	<h5 class="text-muted small text-center">DISCLAIMER</h5>
	<p class="text-muted">
	The tools on this site are provided as is, without any guarantee or waranty. I'd be the first person to admit I am not to be trusted with sensitive information, so I designed these tools not to record any - check the <%= link_to "source code", "https://github.com/mjt145/openadtools", target: "_blank" %> if you don't believe me. These tools are the work of a <%= link_to "passionate amateur", about_path %> so you'll most likely find that something doesn't work properly or that could be improved. In which case <%= link_to "let me know", "https://twitter.com/2michaeltaylor", target: "_blank" %> and I'll see what I can do... no promises though because I just started watching something awesome on <%= link_to "Netflix", "https://www.netflix.com/movie/Sherlock/70202589", target: "_blank" %>...
	</p>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="pull-left text-muted">Built in Foggy London Town by <%= link_to "@2michaeltaylor", "https://twitter.com/2michaeltaylor", target: "_blank" %></p> <a href="https://plus.google.com/113509596071709164639" rel="publisher"></a>
    <p class="pull-right text-muted">Source code available on <%= link_to "GitHub", "https://github.com/mjt145/openadtools", target: "_blank" %></p>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation">
  <div class="container">
  	<!-- Left Navbar -->
  	<ul class="nav navbar-nav navbar-header pull-left">
	  	<li class="navbar-brand">
		    <%= link_to root_path do %>
		    	<span class="glyphicon glyphicon-wrench"></span> OpenAdTools
	    	<% end %>
		  </li>
		</ul>

		<!-- Right Navbar Dropdown-->
		<ul class="nav navbar-nav navbar-header pull-right">
      <li class="dropdown">
        <a class="dropdown-toggle" id="cog" data-toggle="dropdown" href="#">
          <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "About OpenAdTools", about_path %></li>
          <li><%= link_to "Contribute on GitHub", "https://github.com/mjt145/openadtools", target: "_blank" %></li>
          <li><a id="newsletter-signup" href="http://eepurl.com/TWJfL">Sign Up To The Newsletter</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Tools:</li>
          <li><%= link_to "Line Chart", linechart_path %></li>
          <li><%= link_to "Bar Chart", barchart_path %></li>
          <li><%= link_to "Link Tracker", linktracker_path %></li>
          <li><%= link_to "Campaign Calculator", campaigncalculator_path %></li>
          <li><%= link_to "Budget RunRate", budgetrunrate_path %></li>
          <li><%= link_to "A/B Significance", absignificance_path %></li>
          <li><%= link_to "Encoder / Decoder", encoderdecoder_path %></li>
          <li><%= link_to "Tab to CSV", tabtocsv_path %></li>
          <li><%= link_to "Tab to JSON", tabtojson_path %></li>
          <li><%= link_to "CSV to JSON", csvtojson_path %></li>
        </ul>
      </li>
  	</ul>


    
  </div>
</nav>




  

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "OpenAdTools | Open-Source Tools for Performance Marketers." %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Open-Source Tools for Performance Marketers. No Purchase Necessary, No Login Required and No Personal Data Stored." %>">
  <meta name="google-site-verification" content="wUGytZ0fj4hSIQ6b3f7XrxrYPRLnAk7-YdqcnCE2NZs" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <script src='https://cdn.firebase.com/js/client/1.0.15/firebase.js'></script>
  <%= yield(:head) %>
</head>
<body>

 <div id="wrap">

    <div class="container" role="main">

      <%= render 'layouts/navbar' %>

      <%= render 'layouts/messages' %>

      <div class="content">

        <%= yield %>

        <div style="clear: both;">

      </div> <!-- /.content -->

      <%= render 'layouts/disclaimer' %>

    </div> <!-- /.container -->

    <div id="push"></div>

  </div> <!-- /#wrap -->

  <%= render 'layouts/footer' %>

  <%= render 'layouts/analytics' %>

</body>
</html>

app/views/pages/_panels.html.erb
<!-- Line Chart -->
<%= link_to linechart_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Line Chart</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Paste your data straight from excel and instantly create a line chart.
	  </div>
	</div>
<% end %>

<!-- Bar Chart -->
<%= link_to barchart_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Bar Chart</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Paste your data straight from excel and instantly create a bar chart.
	  </div>
	</div>
<% end %>

<!-- Link Tracker -->
<%= link_to linktracker_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Link Tracker</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Quickly add UTM tracking parameters to your marketing campaign links.
	  </div>
	</div>
<% end %>

<!-- Campaign Calculator -->
<%= link_to campaigncalculator_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Campaign Calculator</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Quickly calculate the performance of your marketing campaigns.
	  </div>
	</div>
<% end %>

<!-- A/B Significance -->
<%= link_to absignificance_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">A/B Significance</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Calculate the statistical significance of A/B Tests with the click of a button.
	  </div>
	</div>
<% end %>

<!-- Budget Runrate -->
<%= link_to budgetrunrate_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Budget RunRate</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Calculate how long your budget will last at the current run rate.
	  </div>
	</div>
<% end %>

<!-- Encoder / Decoder -->
<%= link_to encoderdecoder_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Encoder / Decoder</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Paste in your URLs and decode / encode with the click of a button.
	  </div>
	</div>
<% end %>

<!-- Tab to CSV -->
<%= link_to tabtocsv_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Tab to CSV</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Convert Tab Delimited Text into Comma Seperated Values (CSV).
	  </div>
	</div>
<% end %>

<!-- Tab to JSON -->
<%= link_to tabtojson_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">Tab to JSON</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Convert Tab Delimited Text into JavaScript Object Notation (JSON).
	  </div>
	</div>
<% end %>

<!-- Tab to JSON -->
<%= link_to csvtojson_path do %>
	<div class="panel panel-default home-panel">
		<div class="panel-heading">
	    <h3 class="panel-title">
	    	<button type="button" class="btn btn-primary btn-lg btn-block">CSV to JSON</button>
	    </h3>
	  </div>
	  <div class="panel-body text-center">
	    Convert Comma Seperated Values (CSV) into JSON.
	  </div>
	</div>
<% end %>

app/views/pages/about.html.erb
<% content_for :title do %>About OpenAdTools | Open-Source Tools for Performance Marketers.<% end %>
<% content_for :description do %>OpenAdTools is a collection of open-source tools, designed for use by performance marketers. The tools are free to use, don't require you to hand over an email or password and don't store any personal or sensitive information about you or your company.<% end %>

<div class="page-header">
  <h1>About OpenAdTools</h1>
  <p class="lead">Open-source tools for performance marketers.</p>
</div>

<p class="lead">OpenAdTools is a collection of open-source tools, designed for use by performance marketers. The tools are free to use, don't require you to hand over an email or password and don't store any personal or sensitive information about you or your company. Feel free to tweet me with any issues, ideas or insults => <%= link_to "@2michaeltaylor", "https://twitter.com/2michaeltaylor", target: "_blank" %>.

<hr>

<h3>The Story So Far</h3>

<p>I'm <%= link_to "Michael Taylor", "https://www.linkedin.com/in/mjt145" %>, a performance marketer who is slowly building OpenAdTools as I learn how to code. Having been introduced to the power of automation in using Microsoft Excel, I started coding as I dream of one day automating my entire job and taking off to travel the world.</p>

<p>As I got acquainted with the world of programming, I became increasingly dumbfounded by the hard-working, intelligent developers that would put in countless hours answering questions for free on <%= link_to "Stack Overflow", "http://stackoverflow.com/tour", target: "_blank" %>, writing <%= link_to "free tutorials", "http://ruby.railstutorial.org/ruby-on-rails-tutorial-book", target: "_blank" %>, and giving their work away on <%= link_to "GitHub", "https://github.com/", target: "_blank" %>.</p>

<p>Thanks to their irrational generosity, I'm now in a position where I can start paying it forward. This site is a repository for whatever tools I build as I continue to learn. Hopefully you find the site useful and are in a position to pay it forward one day to someone else.</p>

<p>In order to make OpenAdTools as useful as possible, I'm designing every tool on this site under these three main principles:</p>

<h3>1) No Purchase Necessary</h3>
<p>These tools are, and always will be, free to use. Even if I turned evil you could just clone the source code in <%= link_to "GitHub", "https://github.com/mjt145/openadtools", target: "_blank" %> and make your own version. I already have a day job so I don't need to hustle you for dolla, I'm just doin' it for the street cred.</p>

<h3>2) No Login Required</h3>
<p>I don't plan to spam you, so I don't need to force you to hand over your email address. I also don't want to make you remember yet another password, so every tool can be used without the need to login.</p>

<h3>3) No Personal Data Stored</h3>
<p>I want you to be able to use this tool without getting permission from your boss or worrying about my database being hacked, so none of these tools collect or store any valuable or personal data about you or your company.</p>

<h3>Questions, Suggestions, Criticisms</h3>
<p>I'm sure you'll run into issues with some of these tools, or you'll have great ideas about how to improve them. I really appreciate any feedback you can give me - Twitter is the best place to <%= link_to "contact me personally", "https://twitter.com/2michaeltaylor", target: "_blank" %>. If you're a developer (of any skill level) and you want to get involved, then 100% please get in touch - I'd love to have you contribute!</p>

<p>Thanks,</p>

<p>Michael Taylor</p>

app/views/pages/home.html.erb
<% content_for :title do %>OpenAdTools | Open-Source Tools for Performance Marketers. <% end %>
<% content_for :description do %>OpenAdTools is a collection of open-source tools, designed for use by performance marketers. The tools are free to use, don't require you to hand over an email or password and don't store any personal or sensitive information about you or your company.<% end %>

<div class="page-header">
  <h1>OpenAdTools <small>Open-source tools for performance marketers.</small></h1>
  <p>No login required | No sensitive data stored | No purchase necessary.</p>
</div>

<%= render '/pages/panels' %>

app/views/tools/absignificance.html.erb
<% content_for :title do %>A/B Significance by OpenAdTools<% end %>
<% content_for :description do %>Calculate the statistical significance of A/B Tests with the click of a button.<% end %>
<% content_for :tweet do %>"Use A/B Significance by @OpenAdTools to calculate the statistical significance of your A/B Tests => http://bit.ly/OpenAdTools"<% end %>

<div class="page-header">
  <h1>A/B Significance</h1>
  <p class="lead">Calculate the statistical significance of A/B Tests with the click of a button.</p>
</div>

<form onsubmit="return false;" class="form">
  <div class="float-left">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title center">Control Results</h3>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <div>
              <input type="text" id="inputVisC" value="2000">
              <label for="inputVisC">Visitors</label>
          </div>
          <div>
              <input type="text" id="inputConC" value="134">
              <label for="inputConC">Conversions</label>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title center">Test Results</h3>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <div>
              <input type="text" id="inputVisT" value="2000">
              <label for="inputVisT">Visitors</label>
          </div>
          <div>
              <input type="text" id="inputConT" value="165">
              <label for="inputConT">Conversions</label>
          </div>
        </div>
      </div>
    </div>
    <div>
      <button class="submit btn btn-primary btn-lg" onclick="calcSignificance();" >Calculate Significance</button>
    </div>
  </div>

  <div class="panel panel-default float-left">
    <div class="panel-heading">
      <h3 class="panel-title center" id="output-header">Statistically Significant?</h3>
    </div>
    <div class="panel-body">
      <div id="output">
        Enter your test results, then click the 'Calculate Significance' button.
      </div>
    </div>
  </div>
</form>


<%= javascript_tag do %>

function calcSignificance() {
  var visC = document.getElementById('inputVisC').value;
  var conC = document.getElementById('inputConC').value;
  var visT = document.getElementById('inputVisT').value;
  var conT = document.getElementById('inputConT').value;

  var output = document.getElementById('output');
  var outputHeader = document.getElementById('output-header');

  var convRateC = conC / visC;
  var convRateT = conT / visT;

  var diffInConvRate = (convRateT - convRateC) / convRateC * 100;

  var stdErrorC = Math.sqrt(convRateC * (1 - convRateC) / visC);
  var stdErrorT = Math.sqrt(convRateT * (1 - convRateT) / visT);

  var confIntC = 1.96 * stdErrorC;
  var confIntT = 1.96 * stdErrorT;

  var zScore = (convRateC - convRateT) / Math.sqrt(Math.pow(stdErrorC,2) + Math.pow(stdErrorT,2));

  var pValue = "";

  // Convert Z Score into P Value
  var factK = 1;
  var sum = 0;
  var term = 1;
  var k = 0;
  var loopStop = Math.exp(-23);

  while (Math.abs(term) > loopStop) {
    term = 0.3989422804 * Math.pow(-1, k) * Math.pow(zScore, k) / (2 * k + 1) / Math.pow(2, k) * Math.pow(zScore, k + 1) / factK;
    sum += term;
    k++;
    factK *= k;
  }
  sum += 0.5;
  pValue = sum * 100;

  var bodyOutput = "";

  var usersNeeded = (26 * Math.pow(Math.sqrt(convRateC * (1 - convRateC)) / (convRateC * diffInConvRate) , 2));

  // Calculate statistical significance
  if (pValue <= 5 || pValue >= 95) {
    outputHeader.innerHTML = "YES!";

    bodyOutput = "<p class='center'>The test is statistically significant.</p>";

    if (pValue >= 99.99 || pValue <= 0.01) {
      bodyOutput += "<p class='center'>We are close to <em>100%</em> sure that ";
    } else if (pValue <= 5) {
      bodyOutput += "<p class='center'>We are <em>"+(100-pValue).toFixed(2)+"%</em> sure that ";
    } else {
      bodyOutput += "<p class='center'>We are <em>"+pValue.toFixed(2)+"%</em> sure that ";
    }

    if (diffInConvRate > 0) {
      bodyOutput += "the test variation performs <strong>"+diffInConvRate.toFixed(2)+"%</strong> better.</p>";
    } else {
      bodyOutput += "the test variation performs <strong>"+Math.abs(diffInConvRate).toFixed(2)+"%</strong> worse.</p>";
    }

    bodyOutput += "<hr>";
    bodyOutput += "<p>Control Conv. Rate: <strong>"+(convRateC*100).toFixed(2)+"%</strong><small> &plusmn; "+(stdErrorC*100).toFixed(2)+"</small></p>";
    bodyOutput += "<p>Test Conv. Rate: <strong>"+(convRateT*100).toFixed(2)+"%</strong><small> &plusmn; "+(stdErrorT*100).toFixed(2)+"</small></p>";
    bodyOutput += "<p>Difference: <strong>"+diffInConvRate.toFixed(2)+"%</strong></p>";
    bodyOutput += "<p>P Value: <strong>"+(100-pValue).toFixed(2)+"</strong></p>";

  } else {
    outputHeader.innerHTML = "Not Statistically Significant";
    bodyOutput = "<p class='center'>So far we can only be <em>"+pValue.toFixed(2)+"%</em> sure that the <strong>"+diffInConvRate.toFixed(2)+"%</strong> difference in conversion rate is significant.";
    bodyOutput += "<hr>";
    bodyOutput += "<p class='center'>Keep running the test until "+(usersNeeded*1000).toFixed(0)+" more visitors have seen each test variation.";
  }
  output.innerHTML = bodyOutput;
};

<% end %>

app/views/tools/barchart.html.erb
<% content_for :title do %>Bar Chart by OpenAdTools<% end %>
<% content_for :description do %>Paste your data straight from excel and instantly create a slick-looking bar chart.<% end %>

<div class="page-header">
  <h1>Bar Chart</h1>
  <p class="lead">Paste your data straight from excel and instantly create a slick-looking bar chart.</p>
</div>

<br>

<div id="chart"></div>

<br><hr>

<form onsubmit="return false;">
	<button class="submit btn btn-primary btn-lg" onclick="graph();" >Update Chart</button>
	<br><br>
	<h3>Input Data <small>(paste your data straight from excel)</small></h3>
	<div class="col-md-4">
	<textarea class="form-control" rows="10" id="textinput" placeholder="Paste the data you want to display as a bar chart here..." autofocus >5
10
13
19
21
25
22
18
15
13
11
12
15
20
18
17
16
18
23
25</textarea>
<br><br><br>
</div>
</form>


<script type="text/javascript">

var w = 800; // Width
var h = 200; // Height
var p = 2;   // Padding

//Create SVG element
var svg = d3.select("#chart")
            .append("svg")
            .attr("width", w)
            .attr("height", h);

var dataset = document.getElementById('textinput').value.split("\n");
// [ 5, 10, 13, 19, 21, 25, 22, 18, 15, 13,
//  11, 12, 15, 20, 18, 17, 16, 18, 23, 25 ];

var l = dataset.length;

for(var i=0; i<l; i++) { dataset[i] = +dataset[i]; }

var dMax = d3.max(dataset, function(d) { return d; });

var yScale = d3.scale.linear()
                     .range([h, 0])                     
                     .domain([0, dMax]);

svg.selectAll("rect")
   .data(dataset)
   .enter()
   .append("rect")
   .attr("x", function(d, i) {
      return i * (w / l);
    })
   .attr("y", function(d) {
      return yScale(d);
    })
   .attr("width", w / l - p)
   .attr("height", function(d) {
      return h - yScale(d);
    });

// Create data labels
svg.selectAll("text")
   .data(dataset)
   .enter()
   .append("text")
   .text(function(d) {
      return d;
   })
   .attr("x", function(d, i) {
      return i * (w / l) + (w / l - p) / 2;
    })
   .attr("y", function(d) {
      return yScale(d) + 15;
    });

// Function to update graph
function graph() {
	
	dataset = document.getElementById('textinput').value.split("\n");
	l = dataset.length;

  for(var i=0; i<l; i++) { dataset[i] = +dataset[i]; }

  dMax = d3.max(dataset, function(d) { return d; });

  yScale.domain([0, dMax]);

  var rect = svg.selectAll("rect").data(dataset)

  rect.enter()
      .append("rect")
      .transition()
      .duration(1000)
      .attr("x", function(d, i) {
         return i * (w / l);
       })
      .attr("y", function(d) {
         return yScale(d);
       })
      .attr("width", w / l - p)
      .attr("height", function(d) {
        return h - yScale(d);
       });

	rect.transition()
  	   .duration(1000)
  	   .attr("x", function(d, i) {
          return i * (w / l);
        })
       .attr("y", function(d) {
          return yScale(d);
        })
       .attr("width", w / l - p)
       .attr("height", function(d) {
          return h - yScale(d);
        });

  rect.exit()
      .transition()
      .duration(500)
      .attr("height",0)
      .attr("y",h)
      .remove();

  var labels = svg.selectAll("text").data(dataset);

  labels.enter()
        .append("text")
        .transition()
        .duration(1000)
        .text(function(d) {
           return d;
        })
        .attr("x", function(d, i) {
           return i * (w / l) + (w / l - p) / 2;
         })
        .attr("y", function(d) {
           return yScale(d) + 15;
         });

  labels.transition()
      	 .duration(1000)
         .text(function(d) {
            return d;
         })
         .attr("x", function(d, i) {
            return i * (w / l) + (w / l - p) / 2;
          })
         .attr("y", function(d) {
            return yScale(d) + 15;
          });

  labels.exit()
        .transition()
        .duration(500)
        .attr("y",h)
        .remove();
}

</script>
<style>
text {
  dy: 0.75em;
  font-family: sans-serif;
  font-size: 11px;
  fill: white;
  text-anchor: middle;
}
</style>

app/views/tools/encoderdecoder.html.erb
<% content_for :title do %>Encoder / Decoder by OpenAdTools<% end %>
<% content_for :description do %>Paste in your URLs and decode / encode with the click of a button.<% end %>

<div class="page-header">
  <h1>Decoder / Encoder</h1>
  <p class="lead">Paste in your URLs and decode / encode with the click of a button.</p>
</div>

<form onsubmit="return false;">
	<textarea class="form-control" rows="10" id="textinput" placeholder="Paste the URL(s) you want to encode/decode here..." autofocus ></textarea>
	<button class="submit btn btn-primary btn-lg pull-right" onclick="encode();" >Encode</button>
	<button class="submit btn btn-success btn-lg pull-right" onclick="decode();" >Decode</button>
</form>
<br><br><br>

<p class="text-muted">This tool was created by <%= link_to "Eric Meyer", "http://meyerweb.com/eric/tools/dencoder/" %>, before being reproduced and modified here.</p>

<%= javascript_tag do %>

function encode() {
	var obj = document.getElementById('textinput')
	var unencoded = obj.value;
	obj.value = encodeURIComponent(unencoded).replace(/'/g,"%27").replace(/"/g,"%22");
}
function decode() {
	var obj = document.getElementById('textinput')
	var encoded = obj.value;
	obj.value = decodeURIComponent(encoded.replace(/\+/g,  " "));
}

<% end %>